Feature/cvsb 19155
dvsa/cvs-nop pull request #3
Opened 2021-04-12 08:30 UTC by ChrisPeska-BJSS

**CVSB-19155**

CVS_NOP database schema.

2021-04-14 19:27 UTC, SanjeetBJSS submitted a review, later dismissed
Happy to approve

2021-04-15 10:56 UTC, bristol-mike-jones requested changes
Just the details for adding the jar, otherwise very nice.

2021-04-15 10:56 UTC, bristol-mike-jones commented on README.md
> +
The ```mysql-connector-java-8.0.23.jar``` needs to be downloaded from Oracle/MySql and dumped in the project root.  Might be worth saying the platform-independent version can be used, rather than people fretting over which platform-specific jar they need.

2021-04-21 10:04 UTC, bristol-mike-jones approved these changes
LGTM

2021-04-21 12:33 UTC, SanjeetBJSS reviewed
Happy to Approve.

2021-04-21 12:33 UTC, SanjeetBJSS approved these changes

2021-04-21 12:58 UTC, merged