feature/CB2-11231 - Change the accepted maximum length of the Plate Serial Number in NOP
dvsa/cvs-nop pull request #37
Opened 2024-03-20 15:32 UTC by Nat-McCabe-BJSS

## Description

Changes the accepted maximum length for the Plate Serial Number in NOP from 12 to 50

Related issue: [CB2-11231](https://dvsa.atlassian.net/browse/CB2-11231?atlOrigin=eyJpIjoiYmJmODZjNjhmMWNiNDljNDljZGYyZjI4N2QxZWNiZWEiLCJwIjoiaiJ9)

## Before submitting (or marking as "ready for review")

- [x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [x] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [x] Did you make sure to update any documentation relating to this change?

2024-03-20 15:34 UTC, meys-bjss approved these changes, later dismissed

2024-03-20 16:18 UTC, ali-campbell submitted a review, later dismissed
Outstanding work 🥇

2024-03-21 11:45 UTC, reisedawson-bjss requested changes, later dismissed
I don't think this will work - we need to do this change via an extra liquibase changeset. 

In environments where NOP has already been built, when the `BUILD_NOP` job runs the liquibase sql command it will find that the base_database changeset has a different checksum value to the one it executed before and will fail the run. 

Have a look at `00006_alter_technical_record_table.sql` and `00008_alter_make_model_table.sql` for an example of how this should be implemented.

2024-03-21 14:17 UTC, ali-campbell approved these changes

2024-03-22 09:31 UTC, reisedawson-bjss approved these changes
Nice work Nat 🚢🚢🚢

2024-03-22 09:51 UTC, merged